defmodule CheckDay.Repo.Migrations.AddTimezoneToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def change do
    alter table(:users) do
      add :timezone, :text, default: "Etc/UTC"
    end
  end
end
