defmodule CheckDay.Repo.Migrations.AddPodcastAudio do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:digest_runs) do
      add :podcast_audio, :binary
    end
  end

  def down do
    alter table(:digest_runs) do
      remove :podcast_audio
    end
  end
end
