defmodule CheckDay.Repo.Migrations.RemoveOnboardingCompleted do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :onboarding_completed
    end
  end

  def down do
    alter table(:users) do
      add :onboarding_completed, :boolean, default: false
    end
  end
end
