defmodule CheckDay.Repo.Migrations.AddActiveDays do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :active_days, {:array, :bigint}, default: [1, 2, 3, 4, 5, 6, 7]
    end

    alter table(:digest_blocks) do
      add :active_days, {:array, :bigint}, default: [1, 2, 3, 4, 5, 6, 7]
    end
  end

  def down do
    alter table(:digest_blocks) do
      remove :active_days
    end

    alter table(:users) do
      remove :active_days
    end
  end
end
