defmodule CheckDay.Repo.Migrations.AddSkippedDates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :skipped_dates, {:array, :date}, default: []
    end
  end

  def down do
    alter table(:users) do
      remove :skipped_dates
    end
  end
end
