defmodule CheckDay.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :digest_times, :map,
        default:
          "{\"1\":\"07:00\",\"2\":\"07:00\",\"3\":\"07:00\",\"4\":\"07:00\",\"5\":\"07:00\",\"6\":\"07:00\",\"7\":\"07:00\"}"

      modify :active_days, {:array, :bigint}, default: "{1,2,3,4,5,6,7}"
    end

    alter table(:digest_blocks) do
      modify :active_days, {:array, :bigint}, default: "{1,2,3,4,5,6,7}"
    end
  end

  def down do
    alter table(:digest_blocks) do
      modify :active_days, {:array, :bigint}, default: nil
    end

    alter table(:users) do
      modify :active_days, {:array, :bigint}, default: nil
      modify :digest_times, :map, default: nil
    end
  end
end
