defmodule CheckDay.Repo.Migrations.AddDigestBlocksAndUserProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :first_name, :text
      add :onboarding_completed, :boolean, default: false
    end

    create table(:digest_blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :label, :text, null: false
      add :config, :map, default: %{}
      add :position, :bigint, default: 0
      add :enabled, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "digest_blocks_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:digest_blocks, "digest_blocks_user_id_fkey")

    drop table(:digest_blocks)

    alter table(:users) do
      remove :onboarding_completed
      remove :first_name
    end
  end
end
